name: Deploy Oracle OIC Integrations

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Find .iar files
      run: |
        IAR_FILES=$(find . -name "*.iar")
        echo "Found .iar files: $IAR_FILES"
        echo "IAR_FILES=$IAR_FILES" >> $GITHUB_ENV

    - name: Import .iar files to Oracle OIC
      run: |
        for file in $IAR_FILES; do
          echo "Importing $file to Oracle OIC"          
        done
      
    - name: Push if deploy succeeded
      if: success()
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git push origin main
      timeout-minutes: 10  # Increase the timeout as needed        
