name: Deploy Oracle OIC Integrations

on:
  push:
    branches:
      - QA  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Find .iar files
      run: |
        IAR_FILES=$(find . -name "*.iar")
        echo "Found .iar files: $IAR_FILES"

    - name: Import .iar files to Oracle OIC
      run: |
        for file in $IAR_FILES; do
          echo "Importing $file to Oracle OIC"          
        done
